# Database Configuration
spring.datasource.url=jdbc:h2:mem:scrimsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (Auto update database table)
spring.jpa.hibernate.ddl-auto=update
spring.show-sql=true

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf cache (Demo-vukku off-la irukanum)
spring.thymeleaf.cache=false

# Security Settings
spring.security.user.name=admin
spring.security.user.password=admin123